### PR TITLE
Remove unnecessary _n() in theme-style-variations/render-php

### LINKED ISSUE #120: Incorrect use of _n() about style variations
Ref: themes-2024/src/theme-style-variations/render.php?marks=23

Here a string uses "Style variations (%s)" as a plural-aware string ( _n() )

When the count is provided in this way, this should be just a normal string. 
_n() would be the choice if you were to say "%d style variation"//"%d style varitions" instead.

Also, if you use %d rather than %s, then it's easier for a translator to see that this is a number (and not, for instance, the name of some style variation.)

### PR DESCRIPTION
**Pull request by tobifjellner**
Fixes #120 
Props tobifjellner

### CODE REVIEW

File: source/wp-content/themes/wporg-themes-2024/src/theme-style-variations/render.php [hunk 1]
```diff
@@ -19,8 +19,8 @@
 }
 
 $label = sprintf(
-	/* translators: Heading for style variations, %s is the number of styles. */
-	_n( 'Style variations (%s)', 'Style variations (%s)', $count, 'wporg-themes' ),
+	/* translators: Heading for style variations, %d is the number of styles. */
+	__( 'Style variations (%d)', 'wporg-themes' ),
 	$count
 );
```
Comment (dd32) [inline source/wp-content/themes/wporg-themes-2024/src/theme-style-variations/render.php]: I think this should be using `number_format_i18n()` too.

```suggestion
	/* translators: Heading for style variations, %s is the number of styles. */
	__( 'Style variations (%s)', 'wporg-themes' ),
	number_format_i18n( $count )
);
```
